name: Simple CI

on:
  push:
    branches:
      - feature/test-branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List files
        run: ls -la

      - name: Check index.html
        run: test -f index.html && echo "index.html exists" || echo "index.html is missing"
